- name: Install required collections
  ansible.builtin.command:
    cmd: ansible-galaxy collection install -r /tmp/semaphore/repositories/home-server-iac/requirements.yml -p ./collections --force
  connection: local
