- name: Install required collections
  ansible.builtin.command:
    cmd: ansible-galaxy collection install -r semaphore/collections/requirements.yml -p semaphore/collections --force
  connection: local
  args:
    chdir: "{{ playbook_dir }}"
