- name: Install required collections
  ansible.builtin.command:
    cmd: ansible-galaxy collection install -r collections/requirements.yml -p collections --force
  connection: local
  args:
    chdir: "{{ playbook_dir }}"
